eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.201:8761/eureka/
server:
  port: 8791
spring:
  application:
    name: clouddo
  thymeleaf:
    mode: LEGACYHTML5
    cache: false