eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: false
server:
  port: 8762
spring:
  application:
    name: admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true